/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;

import rr.industries.jooq.tables.Filtertable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FiltertableRecord extends TableRecordImpl<FiltertableRecord> implements Record1<String> {

    private static final long serialVersionUID = -1145593204;

    /**
     * Setter for <code>filtertable.guildid</code>.
     */
    public void setGuildid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>filtertable.guildid</code>.
     */
    public String getGuildid() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row1<String> valuesRow() {
        return (Row1) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Filtertable.FILTERTABLE.GUILDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getGuildid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGuildid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FiltertableRecord value1(String value) {
        setGuildid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FiltertableRecord values(String value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FiltertableRecord
     */
    public FiltertableRecord() {
        super(Filtertable.FILTERTABLE);
    }

    /**
     * Create a detached, initialised FiltertableRecord
     */
    public FiltertableRecord(String guildid) {
        super(Filtertable.FILTERTABLE);

        set(0, guildid);
    }
}
