/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import rr.industries.jooq.tables.Globaltags;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GlobaltagsRecord extends TableRecordImpl<GlobaltagsRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 847165695;

    /**
     * Setter for <code>globaltags.tagname</code>.
     */
    public void setTagname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>globaltags.tagname</code>.
     */
    public String getTagname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>globaltags.tagcontent</code>.
     */
    public void setTagcontent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>globaltags.tagcontent</code>.
     */
    public String getTagcontent() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Globaltags.GLOBALTAGS.TAGNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Globaltags.GLOBALTAGS.TAGCONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getTagname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTagcontent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getTagname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTagcontent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobaltagsRecord value1(String value) {
        setTagname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobaltagsRecord value2(String value) {
        setTagcontent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GlobaltagsRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GlobaltagsRecord
     */
    public GlobaltagsRecord() {
        super(Globaltags.GLOBALTAGS);
    }

    /**
     * Create a detached, initialised GlobaltagsRecord
     */
    public GlobaltagsRecord(String tagname, String tagcontent) {
        super(Globaltags.GLOBALTAGS);

        set(0, tagname);
        set(1, tagcontent);
    }
}
