/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import rr.industries.jooq.tables.Guilds;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuildsRecord extends UpdatableRecordImpl<GuildsRecord> implements Record6<Long, Long, String, String, String, Integer> {

    private static final long serialVersionUID = -1008456306;

    /**
     * Setter for <code>guilds.guildid</code>.
     */
    public void setGuildid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>guilds.guildid</code>.
     */
    public Long getGuildid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>guilds.greetchannel</code>.
     */
    public void setGreetchannel(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>guilds.greetchannel</code>.
     */
    public Long getGreetchannel() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>guilds.joinmessage</code>.
     */
    public void setJoinmessage(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>guilds.joinmessage</code>.
     */
    public String getJoinmessage() {
        return (String) get(2);
    }

    /**
     * Setter for <code>guilds.leavemessage</code>.
     */
    public void setLeavemessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>guilds.leavemessage</code>.
     */
    public String getLeavemessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>guilds.prefix</code>.
     */
    public void setPrefix(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>guilds.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(4);
    }

    /**
     * Setter for <code>guilds.filter</code>.
     */
    public void setFilter(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>guilds.filter</code>.
     */
    public Integer getFilter() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, String, String, String, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, String, String, String, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Guilds.GUILDS.GUILDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Guilds.GUILDS.GREETCHANNEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Guilds.GUILDS.JOINMESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Guilds.GUILDS.LEAVEMESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Guilds.GUILDS.PREFIX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Guilds.GUILDS.FILTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getGuildid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getGreetchannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getJoinmessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLeavemessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPrefix();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getFilter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getGuildid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getGreetchannel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getJoinmessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLeavemessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPrefix();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFilter();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value1(Long value) {
        setGuildid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value2(Long value) {
        setGreetchannel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value3(String value) {
        setJoinmessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value4(String value) {
        setLeavemessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value5(String value) {
        setPrefix(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord value6(Integer value) {
        setFilter(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuildsRecord values(Long value1, Long value2, String value3, String value4, String value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuildsRecord
     */
    public GuildsRecord() {
        super(Guilds.GUILDS);
    }

    /**
     * Create a detached, initialised GuildsRecord
     */
    public GuildsRecord(Long guildid, Long greetchannel, String joinmessage, String leavemessage, String prefix, Integer filter) {
        super(Guilds.GUILDS);

        set(0, guildid);
        set(1, greetchannel);
        set(2, joinmessage);
        set(3, leavemessage);
        set(4, prefix);
        set(5, filter);
    }
}
