/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import rr.industries.jooq.tables.Prefixtable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrefixtableRecord extends TableRecordImpl<PrefixtableRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -27582985;

    /**
     * Setter for <code>prefixtable.guildid</code>.
     */
    public void setGuildid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>prefixtable.guildid</code>.
     */
    public String getGuildid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>prefixtable.prefix</code>.
     */
    public void setPrefix(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>prefixtable.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Prefixtable.PREFIXTABLE.GUILDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Prefixtable.PREFIXTABLE.PREFIX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getGuildid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPrefix();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGuildid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPrefix();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrefixtableRecord value1(String value) {
        setGuildid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrefixtableRecord value2(String value) {
        setPrefix(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrefixtableRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrefixtableRecord
     */
    public PrefixtableRecord() {
        super(Prefixtable.PREFIXTABLE);
    }

    /**
     * Create a detached, initialised PrefixtableRecord
     */
    public PrefixtableRecord(String guildid, String prefix) {
        super(Prefixtable.PREFIXTABLE);

        set(0, guildid);
        set(1, prefix);
    }
}
