/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import rr.industries.jooq.tables.Tags;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsRecord extends TableRecordImpl<TagsRecord> implements Record4<String, String, String, Integer> {

    private static final long serialVersionUID = 1667743919;

    /**
     * Setter for <code>tags.guildid</code>.
     */
    public void setGuildid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>tags.guildid</code>.
     */
    public String getGuildid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>tags.tagname</code>.
     */
    public void setTagname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tags.tagname</code>.
     */
    public String getTagname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tags.tagcontent</code>.
     */
    public void setTagcontent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tags.tagcontent</code>.
     */
    public String getTagcontent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tags.ispermanent</code>.
     */
    public void setIspermanent(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>tags.ispermanent</code>.
     */
    public Integer getIspermanent() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Tags.TAGS.GUILDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tags.TAGS.TAGNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tags.TAGS.TAGCONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Tags.TAGS.ISPERMANENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getGuildid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTagname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTagcontent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getIspermanent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getGuildid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTagname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTagcontent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIspermanent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value1(String value) {
        setGuildid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value2(String value) {
        setTagname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value3(String value) {
        setTagcontent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value4(Integer value) {
        setIspermanent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord values(String value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagsRecord
     */
    public TagsRecord() {
        super(Tags.TAGS);
    }

    /**
     * Create a detached, initialised TagsRecord
     */
    public TagsRecord(String guildid, String tagname, String tagcontent, Integer ispermanent) {
        super(Tags.TAGS);

        set(0, guildid);
        set(1, tagname);
        set(2, tagcontent);
        set(3, ispermanent);
    }
}
