/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.TableRecordImpl;

import rr.industries.jooq.tables.Tags;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagsRecord extends TableRecordImpl<TagsRecord> implements Record5<Long, String, String, Integer, Integer> {

    private static final long serialVersionUID = 1835922389;

    /**
     * Setter for <code>tags.guildid</code>.
     */
    public void setGuildid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tags.guildid</code>.
     */
    public Long getGuildid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tags.tagname</code>.
     */
    public void setTagname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tags.tagname</code>.
     */
    public String getTagname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tags.tagcontent</code>.
     */
    public void setTagcontent(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tags.tagcontent</code>.
     */
    public String getTagcontent() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tags.ispermanent</code>.
     */
    public void setIspermanent(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>tags.ispermanent</code>.
     */
    public Integer getIspermanent() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>tags.isglobal</code>.
     */
    public void setIsglobal(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>tags.isglobal</code>.
     */
    public Integer getIsglobal() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, String, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Tags.TAGS.GUILDID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Tags.TAGS.TAGNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Tags.TAGS.TAGCONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Tags.TAGS.ISPERMANENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Tags.TAGS.ISGLOBAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getGuildid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTagname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getTagcontent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getIspermanent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getIsglobal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getGuildid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTagname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getTagcontent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getIspermanent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getIsglobal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value1(Long value) {
        setGuildid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value2(String value) {
        setTagname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value3(String value) {
        setTagcontent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value4(Integer value) {
        setIspermanent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord value5(Integer value) {
        setIsglobal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TagsRecord values(Long value1, String value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TagsRecord
     */
    public TagsRecord() {
        super(Tags.TAGS);
    }

    /**
     * Create a detached, initialised TagsRecord
     */
    public TagsRecord(Long guildid, String tagname, String tagcontent, Integer ispermanent, Integer isglobal) {
        super(Tags.TAGS);

        set(0, guildid);
        set(1, tagname);
        set(2, tagcontent);
        set(3, ispermanent);
        set(4, isglobal);
    }
}
