/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import rr.industries.jooq.DefaultSchema;
import rr.industries.jooq.Indexes;
import rr.industries.jooq.tables.records.FiltertableRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Filtertable extends TableImpl<FiltertableRecord> {

    private static final long serialVersionUID = -1214582823;

    /**
     * The reference instance of <code>filtertable</code>
     */
    public static final Filtertable FILTERTABLE = new Filtertable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FiltertableRecord> getRecordType() {
        return FiltertableRecord.class;
    }

    /**
     * The column <code>filtertable.guildid</code>.
     */
    public final TableField<FiltertableRecord, String> GUILDID = createField("guildid", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>filtertable</code> table reference
     */
    public Filtertable() {
        this(DSL.name("filtertable"), null);
    }

    /**
     * Create an aliased <code>filtertable</code> table reference
     */
    public Filtertable(String alias) {
        this(DSL.name(alias), FILTERTABLE);
    }

    /**
     * Create an aliased <code>filtertable</code> table reference
     */
    public Filtertable(Name alias) {
        this(alias, FILTERTABLE);
    }

    private Filtertable(Name alias, Table<FiltertableRecord> aliased) {
        this(alias, aliased, null);
    }

    private Filtertable(Name alias, Table<FiltertableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SQLITE_AUTOINDEX_FILTERTABLE_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Filtertable as(String alias) {
        return new Filtertable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Filtertable as(Name alias) {
        return new Filtertable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Filtertable rename(String name) {
        return new Filtertable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Filtertable rename(Name name) {
        return new Filtertable(name, null);
    }
}
