/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import rr.industries.jooq.DefaultSchema;
import rr.industries.jooq.Indexes;
import rr.industries.jooq.tables.records.GreetingtableRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Greetingtable extends TableImpl<GreetingtableRecord> {

    private static final long serialVersionUID = 2036663186;

    /**
     * The reference instance of <code>greetingtable</code>
     */
    public static final Greetingtable GREETINGTABLE = new Greetingtable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GreetingtableRecord> getRecordType() {
        return GreetingtableRecord.class;
    }

    /**
     * The column <code>greetingtable.guildid</code>.
     */
    public final TableField<GreetingtableRecord, String> GUILDID = createField("guildid", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>greetingtable.joinmessage</code>.
     */
    public final TableField<GreetingtableRecord, String> JOINMESSAGE = createField("joinmessage", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>greetingtable.leavemessage</code>.
     */
    public final TableField<GreetingtableRecord, String> LEAVEMESSAGE = createField("leavemessage", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>greetingtable</code> table reference
     */
    public Greetingtable() {
        this(DSL.name("greetingtable"), null);
    }

    /**
     * Create an aliased <code>greetingtable</code> table reference
     */
    public Greetingtable(String alias) {
        this(DSL.name(alias), GREETINGTABLE);
    }

    /**
     * Create an aliased <code>greetingtable</code> table reference
     */
    public Greetingtable(Name alias) {
        this(alias, GREETINGTABLE);
    }

    private Greetingtable(Name alias, Table<GreetingtableRecord> aliased) {
        this(alias, aliased, null);
    }

    private Greetingtable(Name alias, Table<GreetingtableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GREETINGINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Greetingtable as(String alias) {
        return new Greetingtable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Greetingtable as(Name alias) {
        return new Greetingtable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Greetingtable rename(String name) {
        return new Greetingtable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Greetingtable rename(Name name) {
        return new Greetingtable(name, null);
    }
}
