/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import rr.industries.jooq.DefaultSchema;
import rr.industries.jooq.Indexes;
import rr.industries.jooq.tables.records.PrefixtableRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Prefixtable extends TableImpl<PrefixtableRecord> {

    private static final long serialVersionUID = -1396233514;

    /**
     * The reference instance of <code>prefixtable</code>
     */
    public static final Prefixtable PREFIXTABLE = new Prefixtable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PrefixtableRecord> getRecordType() {
        return PrefixtableRecord.class;
    }

    /**
     * The column <code>prefixtable.guildid</code>.
     */
    public final TableField<PrefixtableRecord, String> GUILDID = createField("guildid", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>prefixtable.prefix</code>.
     */
    public final TableField<PrefixtableRecord, String> PREFIX = createField("prefix", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>prefixtable</code> table reference
     */
    public Prefixtable() {
        this(DSL.name("prefixtable"), null);
    }

    /**
     * Create an aliased <code>prefixtable</code> table reference
     */
    public Prefixtable(String alias) {
        this(DSL.name(alias), PREFIXTABLE);
    }

    /**
     * Create an aliased <code>prefixtable</code> table reference
     */
    public Prefixtable(Name alias) {
        this(alias, PREFIXTABLE);
    }

    private Prefixtable(Name alias, Table<PrefixtableRecord> aliased) {
        this(alias, aliased, null);
    }

    private Prefixtable(Name alias, Table<PrefixtableRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PREFIXINDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Prefixtable as(String alias) {
        return new Prefixtable(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Prefixtable as(Name alias) {
        return new Prefixtable(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Prefixtable rename(String name) {
        return new Prefixtable(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Prefixtable rename(Name name) {
        return new Prefixtable(name, null);
    }
}
