/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import rr.industries.jooq.tables.Guilds;
import rr.industries.jooq.tables.Perms;
import rr.industries.jooq.tables.Tags;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1903162359;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>guilds</code>.
     */
    public final Guilds GUILDS = rr.industries.jooq.tables.Guilds.GUILDS;

    /**
     * The table <code>perms</code>.
     */
    public final Perms PERMS = rr.industries.jooq.tables.Perms.PERMS;

    /**
     * The table <code>tags</code>.
     */
    public final Tags TAGS = rr.industries.jooq.tables.Tags.TAGS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Guilds.GUILDS,
            Perms.PERMS,
            Tags.TAGS);
    }
}
