/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import rr.industries.jooq.tables.Filtertable;
import rr.industries.jooq.tables.Globaltags;
import rr.industries.jooq.tables.Greetingtable;
import rr.industries.jooq.tables.Perms;
import rr.industries.jooq.tables.Prefixtable;
import rr.industries.jooq.tables.Tags;
import rr.industries.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1063510263;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>filtertable</code>.
     */
    public final Filtertable FILTERTABLE = rr.industries.jooq.tables.Filtertable.FILTERTABLE;

    /**
     * The table <code>globaltags</code>.
     */
    public final Globaltags GLOBALTAGS = rr.industries.jooq.tables.Globaltags.GLOBALTAGS;

    /**
     * The table <code>greetingtable</code>.
     */
    public final Greetingtable GREETINGTABLE = rr.industries.jooq.tables.Greetingtable.GREETINGTABLE;

    /**
     * The table <code>perms</code>.
     */
    public final Perms PERMS = rr.industries.jooq.tables.Perms.PERMS;

    /**
     * The table <code>prefixtable</code>.
     */
    public final Prefixtable PREFIXTABLE = rr.industries.jooq.tables.Prefixtable.PREFIXTABLE;

    /**
     * The table <code>tags</code>.
     */
    public final Tags TAGS = rr.industries.jooq.tables.Tags.TAGS;

    /**
     * The table <code>users</code>.
     */
    public final Users USERS = rr.industries.jooq.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Filtertable.FILTERTABLE,
            Globaltags.GLOBALTAGS,
            Greetingtable.GREETINGTABLE,
            Perms.PERMS,
            Prefixtable.PREFIXTABLE,
            Tags.TAGS,
            Users.USERS);
    }
}
