/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.AbstractKeys;

import rr.industries.jooq.tables.Filtertable;
import rr.industries.jooq.tables.Globaltags;
import rr.industries.jooq.tables.Greetingtable;
import rr.industries.jooq.tables.Perms;
import rr.industries.jooq.tables.Prefixtable;
import rr.industries.jooq.tables.Tags;
import rr.industries.jooq.tables.Users;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SQLITE_AUTOINDEX_FILTERTABLE_1 = Indexes0.SQLITE_AUTOINDEX_FILTERTABLE_1;
    public static final Index GLOBALTAGINDEX = Indexes0.GLOBALTAGINDEX;
    public static final Index GREETINGINDEX = Indexes0.GREETINGINDEX;
    public static final Index PERMSINDEX = Indexes0.PERMSINDEX;
    public static final Index PREFIXINDEX = Indexes0.PREFIXINDEX;
    public static final Index TAGINDEX = Indexes0.TAGINDEX;
    public static final Index USERINDEX = Indexes0.USERINDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 extends AbstractKeys {
        public static Index SQLITE_AUTOINDEX_FILTERTABLE_1 = createIndex("sqlite_autoindex_filtertable_1", Filtertable.FILTERTABLE, new OrderField[] { Filtertable.FILTERTABLE.GUILDID }, true);
        public static Index GLOBALTAGINDEX = createIndex("globaltagindex", Globaltags.GLOBALTAGS, new OrderField[] { Globaltags.GLOBALTAGS.TAGNAME }, true);
        public static Index GREETINGINDEX = createIndex("greetingindex", Greetingtable.GREETINGTABLE, new OrderField[] { Greetingtable.GREETINGTABLE.GUILDID }, true);
        public static Index PERMSINDEX = createIndex("permsindex", Perms.PERMS, new OrderField[] { Perms.PERMS.GUILDID, Perms.PERMS.USERID }, true);
        public static Index PREFIXINDEX = createIndex("prefixindex", Prefixtable.PREFIXTABLE, new OrderField[] { Prefixtable.PREFIXTABLE.GUILDID }, true);
        public static Index TAGINDEX = createIndex("tagindex", Tags.TAGS, new OrderField[] { Tags.TAGS.GUILDID, Tags.TAGS.TAGNAME }, true);
        public static Index USERINDEX = createIndex("userindex", Users.USERS, new OrderField[] { Users.USERS.USERID }, true);
    }
}
