/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq;


import javax.annotation.Generated;

import rr.industries.jooq.tables.Guilds;
import rr.industries.jooq.tables.Perms;
import rr.industries.jooq.tables.Tags;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>guilds</code>.
     */
    public static final Guilds GUILDS = rr.industries.jooq.tables.Guilds.GUILDS;

    /**
     * The table <code>perms</code>.
     */
    public static final Perms PERMS = rr.industries.jooq.tables.Perms.PERMS;

    /**
     * The table <code>tags</code>.
     */
    public static final Tags TAGS = rr.industries.jooq.tables.Tags.TAGS;
}
