/*
 * This file is generated by jOOQ.
*/
package rr.industries.jooq;


import javax.annotation.Generated;

import rr.industries.jooq.tables.Globaltags;
import rr.industries.jooq.tables.Greetingtable;
import rr.industries.jooq.tables.Perms;
import rr.industries.jooq.tables.Prefixtable;
import rr.industries.jooq.tables.Tags;
import rr.industries.jooq.tables.Users;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>globaltags</code>.
     */
    public static final Globaltags GLOBALTAGS = rr.industries.jooq.tables.Globaltags.GLOBALTAGS;

    /**
     * The table <code>greetingtable</code>.
     */
    public static final Greetingtable GREETINGTABLE = rr.industries.jooq.tables.Greetingtable.GREETINGTABLE;

    /**
     * The table <code>perms</code>.
     */
    public static final Perms PERMS = rr.industries.jooq.tables.Perms.PERMS;

    /**
     * The table <code>prefixtable</code>.
     */
    public static final Prefixtable PREFIXTABLE = rr.industries.jooq.tables.Prefixtable.PREFIXTABLE;

    /**
     * The table <code>tags</code>.
     */
    public static final Tags TAGS = rr.industries.jooq.tables.Tags.TAGS;

    /**
     * The table <code>users</code>.
     */
    public static final Users USERS = rr.industries.jooq.tables.Users.USERS;
}
